#!/bin/bash

conda create --name pygmt --channel conda-forge pygmt
conda activate pygmt
pip install IntPyGMT@git+https://github.com/chelle0425/IntPyGMT.git
export PATH=$PATH:/path/to/gs9.26/bin:/path/to/gs9.26/lib
